kind: ConfigMap
apiVersion: v1
metadata:
  name: exampleconfigmap
data:
  nginxconf.conf: |
      server {
      listen 80 default_server;
      server_name _;
      root /home/ec2-user/new_chatapp/fundoo;
      location / {
      proxy_pass http://backendcontainer:8000;
      }
      }